repoUrl: https://helm.elastic.co
projectName: elastic

operator:
  version: 2.6.1

stack:
  version: 0.2.0
  values: |
    eck-kibana:
      spec:
        http:
          tls:
            selfSignedCertificate:
              disabled: true
    eck-agent:
      enabled: true
    eck-fleet-server:
      enabled: true
    eck-beats:
      enabled: true
