projectName: istio
domain: testing.com

istio:
  version: 1.17.1
  namespace: istio-system
  repo: https://istio-release.storage.googleapis.com/charts

kiali:
  version: 1.60.0
  repo: https://kiali.org/helm-charts
  values: |
    cr:
      create: true
      namespace: istio-system
      spec:
        auth:
          strategy: "anonymous"
        external_services:
          tracing:
            enabled: true
            in_cluster_url: 'http://jaeger-operator-jaeger-query.jaeger-operator:16685/jaeger'
            use_grpc: true
            url: 'http://my-jaeger-host/jaeger'
