{{- if .Capabilities.APIVersions.Has "elasticsearch.k8s.elastic.co/v1" -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test-elasticsearch
spec:
  version: 8.6.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
        {{- end -}}

