{{- if .Capabilities.APIVersions.Has "elasticsearch.k8s.elastic.co/v1" -}}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: test-kibana
spec:
  version: 8.6.0
  count: 1
  elasticsearchRef:
    name: test
{{- end -}}
