apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: metallb
  source:
    chart: metallb
    targetRevision: 0.13.7
    repoURL: https://metallb.github.io/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jqPathExpressions:
        - '.spec.conversion.webhook.clientConfig.caBundle'
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jqPathExpressions:
        - '.spec.conversion.webhook.clientConfig.caBundle'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
