apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
spec:
  project: {{ .Values.projectName }}
  source:
    chart: sonarqube
    targetRevision: {{ .Values.version }}
    repoURL: {{ .Values.repoUrl }}
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

