apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  project: {{ .Values.projectName }}
  source:
    path: charts/istio/
    targetRevision: {{ .Values.version }}
    repoURL: {{ .Values.repoUrl }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
