apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  project: {{ .Values.projectName }}
  source:
    path: charts/root/
    targetRevision: HEAD
    repoURL: {{ .Values.repoUrl }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

