projectName: monitoring

kube_prometheus_stack:
  version: 43.3.0
  values: |
    prometheusOperator:
      admissionWebhooks:
        enabled: false
      tls:
        enabled: false
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs: 
          - job_name: 'istiod'
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring
          - job_name: 'envoy-stats'
            metrics_path: /stats/prometheus
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
    grafana:
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: default
              orgId: 1
              folder:
              type: file
              disableDeletion: true
              editable: false
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          # Ref: https://istio.io/latest/docs/ops/integrations/grafana/ 
          istio-mesh:
            gnetId: 7639
            revision: 111
            datasource: Prometheus
          istio-service:
            gnetId: 7636
            revision: 111
            datasource: Prometheus
          istio-workload:
            gnetId: 7630
            revision: 111
            datasource: Prometheus
          istio-perfomance:
            gnetId: 11829
            revision: 111
            datasource: Prometheus
          istio-control-plane:
            gnetId: 7645
            revision: 111
            datasource: Prometheus
