{{- if .Capabilities.APIVersions.Has "metallb.io/v1beta1" -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minikube-pool
  namespace: metallb-system
spec:
  addresses:
    - "192.168.49.2-192.168.49.2"
{{- end -}}
