{{- if .Capabilities.APIVersions.Has "metallb.io/v1beta1" -}}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
{{- end -}}
