{{- if .Capabilities.APIVersions.Has "metallb.io/v1beta1" -}}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: minikube-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - minikube-pool
{{- end -}}
