apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
spec:
  project: {{ .Values.projectName }}
  source:
    chart: argo-events
    targetRevision: {{ .Values.argo_events.version }}
    repoURL: {{ .Values.repoUrl }}
    {{- include "lib.helmValues" .Values.argo_events.values | nindent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

