apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator-crds
spec:
  project: {{ .Values.projectName }}
  source:
    chart: eck-operator-crds
    targetRevision: {{ .Values.version }}
    repoURL: {{ .Values.repoUrl }}
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

