apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
spec:
  project: {{ .Values.projectName }}
  source:
    chart: eck-operator
    targetRevision: {{ .Values.version }}
    repoURL: {{ .Values.repoUrl }}
    {{- include "lib.helmValues" .Values.operator.values | nindent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

