apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-crd
spec:
  project: {{ .Values.projectName }}
  source:
    repoURL: https://download.elastic.co/downloads/eck/{{ .Values.version }}/crds.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

