apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
spec:
  project: {{ .Values.projectName }}
  source:
    chart: eck-stack
    targetRevision: {{ .Values.stack.version }}
    repoURL: {{ .Values.repoUrl }}
    {{- include "lib.helmValues" .Values.stack.values | nindent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
