apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
spec:
  project: {{ .Values.projectName }}
  source:
    chart: eck-operator
    targetRevision: {{ .Values.version }}
    repoURL: {{ .Values.repoUrl }}
    {{- include "lib.helmValues" .Values.operatorValues | nindent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: elastic-operator.elastic-system.k8s.elastic.co
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

