{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: db-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
      - '{{ .Values.domain }}'
      port:
        name: tcp-postgresql
        number: 5432
        protocol: TCP
{{- end -}}

