{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: db-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.domain }}
  gateways:
    - db-gateway
  http:
    - route:
        - destination:
            host: cockroachdb-public
            port:
              number: 26257
{{- end -}}
