{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: db-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.domain }}
  gateways:
    - db-gateway
  tcp:
    - match:
      - port: 5432
      route:
        - destination:
            host: postgresql
            port:
              number: 5432
{{- end -}}
