apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod
spec:
  project: {{ .Values.projectName }}
  source:
    chart: istiod
    repoURL: {{ .Values.istio.repo }}
    targetRevision: {{ .Values.istio.version }}
    helm:
      #Required for some unknown bug
      releaseName: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.istio.namespace }}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


