apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  project: {{ .Values.projectName }}
  source:
    chart: postgresql
    targetRevision: 12.2.2
    repoURL: {{ .Values.repoUrl }}
    {{- include "lib.helmValues" .Values.values | nindent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

