repoUrl: https://charts.cockroachdb.com/
projectName: cockroachdb

values: |
  statefulset:
    replicas: 2
    resources:
      limits:
        memory: "1.5Gi"
      requests:
        memory: "1Gi"
  conf:
    cache: "500Mi"
    max-sql-memory: "500Mi"
  tls:
    enabled: false
  init:
    provisioning:
      enabled: true
      users:
        - name: baris
          options: [LOGIN]
      databases:
        - name: plant
