repoUrl: https://charts.bitnami.com/bitnami
projectName: postgresql
domain: 188.132.128.77
namespace: postgresql

values: |
  auth:
    postgresPassword: password
    database: bitki
  primary:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: "shared"
