repoUrl: https://charts.cockroachdb.com/
projectName: cockroachdb

values: |
  statefulset:
    replicas: 1
    resources:
      limits:
        memory: "1.5Gi"
      requests:
        memory: "1Gi"
  conf:
    cache: "500Mi"
    max-sql-memory: "500Mi"
    single-node: true
  tls:
    enabled: false
