repoUrl: https://charts.cockroachdb.com/
projectName: cockroachdb

values: |
  statefulset:
    resources:
      limits:
        memory: "4Gi"
      requests:
        memory: "4Gi"
  conf:
    cache: "1Gi"
    max-sql-memory: "1Gi"
  tls:
    enabled: false
