apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.projectName }}
  namespace: argo-cd
spec:
  sourceRepos:
  - https://prometheus-community.github.io/helm-charts
  destinations:
  - namespace: monitoring
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
